apiVersion: v1
kind: Pod
metadata:
  name: andrei
  labels:
    app: sleeper
    role: test
spec:
  containers:
  - name: sleeper
    image: busybox:latest
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  restartPolicy: Always
  nodeSelector:
    role: andrei