---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  limits:
    cpu: "64"
    memory: 512Gi
  template:
    spec:
      nodeClassRef:
        group: karpenter.proxmox.sinextra.dev
        kind: ProxmoxNodeClass
        name: default
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.proxmox.sinextra.dev/instance-family"
          operator: In
          values: ["c1"]
        # - key: "karpenter.sh/capacity-type"
        #   operator: In
        #   values: ["spot", "on-demand", "reserved"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["rnd-1", "rnd-2"]
---
apiVersion: karpenter.proxmox.sinextra.dev/v1alpha1
kind: ProxmoxNodeClass
metadata:
  name: default
spec:
  template: talos
  blockDevicesStorageID: zfs
  tags:
    - talos-k8s-proxmox
    - karperter
